---
title: "Предобработка данных теста 'Ментальное вращение'"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 10)
```

```{r}
suppressMessages(library("DBI"))
suppressMessages(library("RMySQL"))
suppressMessages(library("tibble"))
suppressMessages(library("dplyr"))
suppressMessages(library("writexl"))
```


```{r}
correct_answers <- c(1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1)
```


```{r}
# База данных moodle.tsu.su
db_moodle_tsu <- dbConnect(RMySQL::MySQL(),
                user="root",
                password="gweiE5idCZTEbR3iKzUY6",
                dbname="bitnami_moodle",
                host="92.63.64.76",
                port=as.numeric(33061),
                encoding = "UTF-8")

dbGetQuery(db_moodle_tsu,'SET NAMES utf8') #для установления кодировки, если появляются "???" в данных
```


```{r}
mrot <- dbGetQuery(db_moodle_tsu,'SELECT userid, data FROM mdl_mrot_data;')
mrot_answers <- strsplit(mrot$data, " ", fixed = F)
mrot_answers <- as.data.frame(matrix(unlist(mrot_answers), ncol = 66, byrow = T))
mrot_answers[, c(65, 66)] <- NULL
names(mrot_answers)[c(T, F)] <- paste0("a", 1:length(names(mrot_answers)[c(T, F)]))
names(mrot_answers)[c(F, T)] <- paste0("t", 1:length(names(mrot_answers)[c(F, T)]))
mrot_answers <- lapply(mrot_answers, as.numeric)
mrot <- cbind(mrot, mrot_answers)
mrot$data <- NULL
```


```{r}
mrot_results <- select(mrot, userid)

mrot_results$time_all <- rowSums(select(mrot, starts_with("t")))
mrot_results$time_all_mean <- rowMeans(select(mrot, starts_with("t")))

mrot_results$time_static <- rowSums(select(mrot, starts_with("t"))[, 1:16])
mrot_results$time_static_mean <- rowMeans(select(mrot, starts_with("t"))[, 1:16])
mrot_results$time_animation <- rowSums(select(mrot, starts_with("t"))[, 17:32])
mrot_results$time_animation_mean <- rowMeans(select(mrot, starts_with("t"))[, 17:32])

mrot_results$right_all <- rowSums(select(mrot, starts_with("a")) == matrix(rep(correct_answers, nrow(mrot)), ncol = 32, byrow = T))
mrot_results$right_static <- rowSums(select(mrot, starts_with("a"))[, 1:16] == matrix(rep(correct_answers[1:16], nrow(mrot)), ncol = 16, byrow = T))
mrot_results$right_animation <- rowSums(select(mrot, starts_with("a"))[, 17:32] == matrix(rep(correct_answers[17:32], nrow(mrot)), ncol = 16, byrow = T))

mrot_results$error_all <- length(correct_answers) - mrot_results$right_all
mrot_results$error_static <- length(correct_answers[1:16]) - mrot_results$right_static
mrot_results$error_animation <- length(correct_answers[17:32]) - mrot_results$right_animation
```

```{r}
mrot_all <- cbind(mrot, select(mrot_results, -userid))
```


```{r}
write_xlsx(mrot, "./data/mrot_raw.xlsx")
write_xlsx(mrot_results, "./data/mrot_results.xlsx")
write_xlsx(mrot_all, "./data/mrot_all.xlsx")
```
